---
title: "Team-Based Interdisciplinary Research"
author: "Kiona Ogle & Katharyn Duffy"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: https://github.com/katharynduffy/TeamBasedResearch
description: "Coming soon"
---

# Welcome to Team-Based Interdisciplinary Research

## The Goals of this Course

The purpose of this course is to prepare **you** for a future career that involves collaborative or team-based approaches to scientific research and problem solving. Through this course you will gain expertise in team-science concepts and approaches, including:
  + team building,
  + team diversity and social sensitivity,
  + effective individual and team communication,
  + collaboration tools and strategies,
  + constructive/destructive group behaviors,
  + conflict resolution,
  + individual and team time/project management,
  + creating effective team policies, procedures, and expectations, including authorship and data sharing policies,
  + assessing team functioning,
  + collaborative manuscript and proposal writing, and
  + collaborative presentations.

  As teams you will employ these team-science skills to develop an interdisciplinary research proposal, to conduct preliminary research that aligns with the proposed project, and to develop and deliver an oral presentation of their proposed research and preliminary results. Towards developing a research proposal and conducting preliminary analyses, students will work together to develop the team’s rules of conduct and a project plan or roadmap. The team will work together to review relevant literature, to initiate preliminary analyses, coding, or modeling, to identify individual and team-oriented tasks, and to set milestones. The course will culminate with submission of a fully developed research proposal and team presentations of their proposed research project, preliminary results, and potential future directions.
